config/routes.rb
Rails.application.routes.draw do

  # Exercise 6.13 : ActionCable --------------------------------/
  mount ActionCable.server => '/cable'

  # Home      --------------------------------------------------/
  root 'simple_pages#landing_page'

  # Users     --------------------------------------------------/
  devise_for :users, controllers: { registrations: "user_registrations" }

  # Products  --------------------------------------------------/
  resources :products do
    resources :comments
  end

  # Orders    --------------------------------------------------/
  resources :orders, only: [:index, :show, :create, :destroy]

  # Demo      --------------------------------------------------/
  get '/demo', to: redirect('pages/demo.html')

  # Response ---------------------------------------------------/
  post 'simple_pages/thank_you'

  # Contact ---------------------------------------------------/
  get '/contact', to: 'simple_pages#contact'

  # Stripe    --------------------------------------------------/
  post 'payments/create'

  # Admin     --------------------------------------------------/
  get '/table', to: 'products#table'
  get '/users', to: 'users#index'

end

app/views/partials/_footer.html.erb
<!-- begin footer -->
<footer class="container-fluid text-center">
  <div class="row">
    <div class="col col-xs-12">
      <!-- Notice -->
      <% if notice %>
        <span class="notice"><%= notice %></span>
      <% end %>
      <!-- Alert -->
      <% if alert %>
        <span class="alert"><%= alert %></span>
      <% end %>
      <!-- Branding -->
      <% if !alert && !notice %>
        <span id="azjem"> &copy; 2018 AZ-JEM </span>
      <% else %>
        <span id="azjem" style="display: none"> &copy; 2018 AZ-JEM </span>
      <% end %>
    </div>
  </div>
</footer>
<!-- end footer -->

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <p class="navbar-brand">
        <%= link_to root_path, title:"Home...", toggle:"tooltip", "data-placement":"bottom" do %>
          <span id="brand">
            <strong>
              <em>Polar Clock Shop</em>
            </strong>
          </span>
        <% end %>
      </p>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <!-- search form -->
      <%= form_with(url: products_path, method: "get", local: true, class: "navbar-form navbar-left") do |form| %>
        <div class="field form-group">
          <%= form.text_field :q, id: "q", value: params[:q], class: "form-control", "placeholder": "Search products..." %>
        </div>
        <div class="actions form-group">
          <button type="submit" name="commit" value="Go" class="btn btn-primary" data-disable-with="Go" >
            <i style="font-size: 2rem;" class="fas fa-search"></i>
          </button>
        </div>
      <% end %>
      <!-- </form> -->

      <!-- navigation anchors -->
      <ul class="nav navbar-nav navbar-right">
        <!-- products -->
        <li class="<%= 'active' if current_page?(products_path) %>">
          <%= link_to products_path, title:"List all products...", toggle:"tooltip", "data-placement":"bottom" do %>
            <i class="fas fa-cubes"></i> Products
          <% end %>
        </li>
        <!-- orders -->
        <li class="<%= 'active' if current_page?(orders_path) %>">
          <%= link_to orders_path,
            title:"Show orders...", toggle:"tooltip", "data-placement":"bottom" do %>
            <i class="fas fa-shopping-cart"></i> Orders
          <% end %>
        </li>
        <!-- demo -->
        <li class="<%= 'active' if current_page?(demo_path) %>">
          <%= link_to demo_path, title:"Running demonstration...", toggle:"tooltip", "data-placement":"bottom" do %>
            <i class="fas fa-clock"></i> Demo
          <% end %>
        </li>
        <!-- contact -->
        <li class="<%= 'active' if current_page?(contact_path) %>">
          <%= link_to contact_path, title:"Contact...", toggle:"tooltip", "data-placement":"bottom" do %>
            <i class="fas fa-envelope"></i> Contact
          <% end %>
        </li>
        <!-- Authentication -->
        <% if current_user %>
          <!-- MANAGE USER INFO -->
          <li class="<%= 'active' if current_page?(edit_user_registration_path) %>">
            <%= link_to edit_user_registration_path, method: :get, title:"Edit your info...", toggle:"tooltip", "data-placement":"bottom" do %>
              <i class="fas fa-edit"></i> Account
            <% end %>
          </li>
          <!-- SIGN OUT -->
          <li>
            <%= link_to destroy_user_session_path, method: :delete, title:"End session", toggle:"tooltip", "data-placement":"bottom" do %>
              <i class="fas fa-unlock"></i> Sign Out
            <% end %>
          </li>
        <% else %>
          <!-- SIGN IN or SIGN UP -->
          <li class="<%= 'active' if current_page?(new_user_session_path) %>">
            <%= link_to new_user_session_path, method: :get, title:"Sign-in OR Sign-up", toggle:"tooltip", "data-placement":"bottom" do %>
              <i class="fas fa-lock"></i> Sign In
            <% end %>
          </li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/partials/_stripe_checkout_button.html.erb
<script
  src="https://checkout.stripe.com/checkout.js" class="stripe-button"
  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
  data-name="<%= @product.name %>"
  data-description="<%= @product.description %>"
  data-email="<%= @user_tag %>"
  data-amount="<%= (@product.price * 100).to_int %>"
  data-image="https://stripe.com/img/documentation/checkout/marketplace.png"
  data-locale="auto">
</script>