config/routes.rb
Rails.application.routes.draw do

  # Exercise 6.13 : ActionCable --------------------------------/
  mount ActionCable.server => '/cable'

  # Home      --------------------------------------------------/
  root 'simple_pages#landing_page'

  # Users     --------------------------------------------------/
  devise_for :users, controllers: { registrations: "user_registrations" }

  # Products  --------------------------------------------------/
  resources :products do
    resources :comments
  end

  # Orders    --------------------------------------------------/
  resources :orders, only: [:index, :show, :create, :destroy]

  # Demo      --------------------------------------------------/
  get '/demo', to: redirect('pages/demo.html')

  # Response ---------------------------------------------------/
  post 'simple_pages/thank_you'

  # Contact ---------------------------------------------------/
  get '/contact', to: 'simple_pages#contact'

  # Stripe    --------------------------------------------------/
  post 'payments/create'

  # Admin     --------------------------------------------------/
  get '/table', to: 'products#table'
  get '/users', to: 'users#index'

end

app/models/product.rb
class Product < ApplicationRecord

  validates :name, presence: true, length: { in: 3..20 }
  validates :description, presence: true
  # range is not inclusive
  # therefore {1..99} cent price range
  validates :price, presence: true, numericality: { greater_than: 0.0, less_than: 1.0 }

  has_many :orders

  # -------------------------------------------------- /
  # Exercise 5.7
  # -------------------------------------------------- /
  has_many :comments

  def highest_rating_comment
    comments.rating_desc.first
  end

  def average_rating
    comments.rating_asc.average(:rating)
  end

  def lowest_rating_comment
    comments.rating_asc.first
  end
  # -------------------------------------------------- /

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :set_product, only: [:show, :edit, :update, :destroy]
  # Authentication
  before_action :authenticate_user!, only: [:edit, :update, :destroy]

  def table
    @products = Product.all.paginate(page: params[:page], per_page: @table_pagination)
  end

  # GET /products
  # GET /products.json
  def index
    # ----------------------------------------------------------------- /
    # Query subset?
    # ----------------------------------------------------------------- /
    if params[:q]
      search_term = params[:q]
      # ----------------------------------------------------------------- /
      # Equalize Dev / Prod query behavior
      # ----------------------------------------------------------------- /
      if Rails.env.production?
        # Postgres
        record_set = Product.where("name ILIKE ?", "%#{search_term}%")
      else
        # SQLite
        record_set = Product.where("name LIKE ?", "%#{search_term}%")
      end
      # ----------------------------------------------------------------- /
    else
      # Pagination
      record_set = Product.all
    end
    # paginate records
    @products = record_set.paginate(page: params[:page], per_page: @product_pagination)
  end

  # GET /products/1
  # GET /products/1.json
  def show
    # set title
    # @page_title = @product.name
    # Exercise 5.8
    # add pagination
    @comments = @product.comments.order("created_at DESC").paginate(page: params[:page], per_page: @comment_pagination)
    # product scoped comment counters...
    $redis.set "#{@product.id}_comment_count", @comments.count
  end

  # Authorization ---------------------------------------- /
  # a - Heroku fails with this leading block
  # b - incompatible with before_action
  # c - this "imperative" solution just works...
  load_and_authorize_resource

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :price)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
  # Exercise 6.11 : Caching
  def cache_key_for_products
    count          = @products
    # No, I'm not sure exactly what's happening in this line...
    # But I believe it returns the update time stamp in universal coordinated time :
    max_updated_at = Product.maximum(:updated_at).try(:utc).try(:to_s, :number)
    # return the cache key
    key = "products/all-#{count}-#{max_updated_at}"

    # puts '*' * 100
    # puts key
    # puts '*' * 100

    key
  end
end

app/views/products/_comments.html.erb
<!-- Exercise 5.8 -->
<div class="product-reviews">

  <% @comments.each do |comment| %>
    <%= render comment %>
  <% end %>

  <% if @comments.count > @comment_pagination %>
    <div class="row">
      <div class="col col-md-12 text-center">
        <%= will_paginate @comments, renderer: BootstrapPagination::Rails %>
      </div>
    </div>
  <% end %>

</div>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :image_url %>
    <%= form.text_field :image_url, id: :product_image_url, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price, id: :product_price, class: "form-control" %>
  </div>

  <div class="actions form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/products/_new_comment.html.erb
<!-- Exercise 5.8 -->

<% if signed_in? %>

  <div class="comment-form">
  <h3 id="comment-caption"><em>Add a review:</em></h3>

  <!-- Exercise 6.10 : Ajax -->
  <%= form_for([@product, @product.comments.build], remote: true) do |f| %>

    <div class="row">
      <div class="col-sm-12">

        <div>
          <%= f.label :body, "Comments" %>
          <%= f.text_area :body, class: "form-control" %>
        </div>
        <br>

        <div>
          <%= f.label :rating %>
          <span class="rating"></span>
        </div>
        <br>

      </div>
    </div>

    <%= f.submit "Submit review", class: "btn btn-primary" %>

  <% end %>
  </div>

<% end %>

app/views/products/edit.html.erb
<h3>Editing Product</h3>

<hr>
<%= render 'form', product: @product %>
<hr>

<%= link_to 'Show', @product, class:"btn btn-md btn-info" %> |
<%= link_to 'Products', products_path, class:"btn btn-md btn-default" %>

app/views/products/index.html.erb
<!-- veiw caption -->
<div class="row">
  <div class="col-sm-2">
    <h3>
      <em>
        <strong>Products</strong>
      </em>
    </h3>
  </div>
  <!-- admin controls -->
  <% if signed_in? && current_user.admin? %>
    <div class="col-sm-2 col-sm-offset-8">
      <p class="title-control"><%= link_to 'Table View...', table_path, class:"btn btn-md btn-default center-block" %></p>
    </div>
  <% end %>
</div>

<!-- TODO: move to stylesheet -->
<hr style="margin: 0 auto;">
<br>

<!-- Outer products cache block  -->
<% cache(cache_key_for_products) do %>

  <div class="row">
    <% @products.each do |product| %>
      <!-- Inner product cache block -->
      <% cache product do %>

        <div class="col col-md-4 col-sm-6 col-xs-12">
          <div class="product-title text-center"><%= product.name %></div>
          <div class="product-image">
            <%=
              link_to image_tag(product.image_url,
              class: "img-responsive center-block"),
              {controller: 'products', action: 'show', id: product.id}
            %>
          </div>
          <p class="product-desc"><%= product.description %></p>
          <p class="product-title text-center"><%= number_to_currency(product.price) %></p>
          <br>
        </div>

      <% end %>
      <!-- end : Inner product cache block -->
    <% end %>
  </div>

<% end %>
<!-- end : Outer products cache block  -->

<!-- TODO: move to stylesheet -->
<hr style="margin-top: 0;">

<% if @products.count > @product_pagination %>
  <div class="row">
    <div class="col col-md-12 text-center">
      <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<h3>New Product</h3>

<hr>
<%= render 'form', product: @product %>
<hr>

<%= link_to 'Products', products_path, class:"btn btn-md btn-default" %>

app/views/products/show.html.erb
<h3><%= @product.name %></h3>

<hr>

<!-- Exercise 6.14 : product id is passed... -->
<div class="row product-row" data-product-id="<%= @product.id %>">

  <!-- product image -->
  <div class="col col-sm-3">
    <% @zoomImage = 'z' + @product.image_url%>
    <%= image_tag(@zoomImage, class: "img-responsive img-zoom", data_zoom_image: @zoomImage) %>
  </div>

  <!-- product data -->
  <div class="col col-sm-9">

    <p>
      <%= @product.description %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= number_to_currency(@product.price) %>
    </p>

    <div id="average-rating" class="rated" data-score="<%= @product.average_rating %>"></div>

    <p id="average-rating-text">
      <% if @product.average_rating %>
        <em>Average rating:</em>
        <%= number_to_human(@product.average_rating) %>
      <% else %>
        <em>No user ratings yet...</em>
      <% end %>
    </p>

    <!-- Exercise 6.5 -->
    <% if current_user %>
      <%= form_with(url: '/payments/create') do |form| %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= render partial: "partials/stripe_checkout_button" %>
      <% end %>
    <% end %>

    <% if signed_in? && current_user.admin? %>
      <%= link_to 'Edit product...', edit_product_path(@product), class:"btn btn-md btn-default" %>
    <% end %>

  </div>

</div>

<!-- Exercise 5.8 -->
<%= render 'new_comment' %>
<!-- Exercise 6.13 : ActionCable... -->
<% if @comments.count > 0 %>
  <h3>Reviews : <span id="comment-cnt"><%= @comments.count %></span></h3>
  <div class="alert alert-info" style="display:none" role="alert">
    A new comment was posted...
  </div>
  <%= render 'comments' %>
<% end %>

app/views/products/table.html.erb
<h3>
  <em>
    <strong>Products</strong>
  </em>
</h3>

<div class="table-responsive">
  <table class="table table-condensed">
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Image url</th>
        <th>Price</th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <!-- fields... -->
          <td><%= product.name %></td>
          <td><%= product.description %></td>
          <td><%= product.image_url %></td>
          <td><%= number_to_currency(product.price) %></td>
          <!-- actions... -->
          <td>
            <!-- <i class="fas fa-eye"></i> -->
            <%= link_to 'Show', product,
              class:"btn btn-info"
            %>
          </td>
          <!-- administrative links -->
          <% if signed_in? && current_user.admin? %>
            <td>
              <!-- <i class="fas fa-pencil-alt"></i> -->
              <%= link_to 'Edit', edit_product_path(product),
                class:"btn btn-success"
              %>
            </td>
            <td>
              <!-- <i class="fas fa-trash"></i> -->
              <%= link_to 'X', product,
                method: :delete, data: { confirm: 'Are you sure?' },
                class:"btn btn-danger"
              %>
            </td>
          <% end %>

        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<% if signed_in? && current_user.admin? %>
  <%= link_to 'New', new_product_path,
    class:  "btn btn-default",
    title:  "Add a new product",
    toggle: "tooltip",
    "data-placement": "bottom"
  %>
<% end %>


<% if @products.count > @table_pagination %>
  <hr>
  <div class="row">
    <div class="col col-md-12 text-center">
      <%= will_paginate @products, renderer: BootstrapPagination::Rails %>
    </div>
  </div>
<% end %>